# LLM Configuration
llm:
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 4096
  context_window: 128000

# API Configuration
api:
  base_url: "https://api.openai.com/v1"
  timeout: 30

# OpenAI Configuration
openai:
  api_key: ${OPENAI_API_KEY}

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/app.log"

# Discussion Configuration
discussion:
  max_turns: 10
  idea_saturation_threshold: 3

# Principles Configuration
principles:
  version_control_file: "data/principles_version_control.json"

# Data Usage Note
data_usage:
  note: "Data sent to the OpenAI API will not be used to train or improve OpenAI models. API data may be retained for up to 30 days for abuse monitoring purposes, after which it will be deleted (unless otherwise required by law)."
